In [1]:
import pandas as pd

In [2]:
# URLs of the team pages you want to scrape
team_urls = [
    'https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats',
    'https://fbref.com/en/squads/18bb7c10/Arsenal-Stats',
    'https://fbref.com/en/squads/822bd0ba/Liverpool-Stats',
    'https://fbref.com/en/squads/8602292d/Aston-Villa-Stats',
    'https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats',
    'https://fbref.com/en/squads/19538871/Manchester-United-Stats',
    'https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats',
    'https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats',
    'https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats',
    'https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats',
    'https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats',
    'https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats',
    'https://fbref.com/en/squads/fd962109/Fulham-Stats',
    'https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats',
    'https://fbref.com/en/squads/d3fd31cc/Everton-Stats',
    'https://fbref.com/en/squads/cd051869/Brentford-Stats',
    'https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats',
    'https://fbref.com/en/squads/e297cd13/Luton-Town-Stats',
    'https://fbref.com/en/squads/943e8050/Burnley-Stats',
    'https://fbref.com/en/squads/1df6b87e/Sheffield-United-Stats'
]

# Initialize an empty DataFrame to store all data
all_teams_data = pd.DataFrame()

for url in team_urls:
    # Extract the team ID from the URL to use as an identifier
    team_id = url.split('/')[-1]
    
    try:
        # Attempt to read the specified table
        df = pd.read_html(url, attrs={"id": "stats_standard_9"})[0]
        # Add a column to identify the team
        df['TeamID'] = team_id
        # Append to the main DataFrame
        all_teams_data = pd.concat([all_teams_data, df], ignore_index=True)
        print(f"Data for {team_id} fetched and added.")
    except ValueError:
        print(f"No table found for {team_id} or connection issues.")

Data for Manchester-City-Stats fetched and added.
Data for Arsenal-Stats fetched and added.
Data for Liverpool-Stats fetched and added.
Data for Aston-Villa-Stats fetched and added.
Data for Tottenham-Hotspur-Stats fetched and added.
Data for Manchester-United-Stats fetched and added.
Data for Newcastle-United-Stats fetched and added.
Data for West-Ham-United-Stats fetched and added.
Data for Chelsea-Stats fetched and added.
Data for Bournemouth-Stats fetched and added.
Data for Wolverhampton-Wanderers-Stats fetched and added.
Data for Brighton-and-Hove-Albion-Stats fetched and added.
Data for Fulham-Stats fetched and added.
Data for Crystal-Palace-Stats fetched and added.
Data for Everton-Stats fetched and added.
Data for Brentford-Stats fetched and added.
Data for Nottingham-Forest-Stats fetched and added.
Data for Luton-Town-Stats fetched and added.
Data for Burnley-Stats fetched and added.
Data for Sheffield-United-Stats fetched and added.

In [3]:
all_teams_data.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
              Player             Nation                Pos                Age
0     Julián Álvarez             ar ARG              MF,FW             24-092
1              Rodri             es ESP                 MF             27-315
2            Ederson             br BRA                 GK             30-259
3         Phil Foden            eng ENG              FW,MF             23-340
4        Kyle Walker            eng ENG                 DF             33-340

  Unnamed: 4_level_0 Playing Time               Performance       ...  \
                  MP       Starts     Min   90s         Gls  Ast  ...
0               33.0           31  2628.0  29.2         9.0  8.0  ...
1               30.0           30  2571.0  28.6         7.0  7.0  ...
2               30.0           30  2537.0  28.2         0.0  0.0  ...
3               31.0           29  2518.0  28.0        16.0  7.0  ...
4               28.0           27  2428.0  27.0         0.0  4.0  ...

  Per 90 Minutes                                          Unnamed: 33_level_0  \
            G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG             Matches
0           0.27   0.55  0.41  0.22   0.63  0.38     0.60             Matches
1           0.25   0.49  0.13  0.11   0.24  0.13     0.24             Matches
2           0.00   0.00  0.00  0.00   0.00  0.00     0.00             Matches
3           0.57   0.82  0.33  0.27   0.60  0.33     0.60             Matches
4           0.00   0.15  0.01  0.10   0.11  0.01     0.11             Matches

                  TeamID Playing Time
                                   MP
0  Manchester-City-Stats          NaN
1  Manchester-City-Stats          NaN
2  Manchester-City-Stats          NaN
3  Manchester-City-Stats          NaN
4  Manchester-City-Stats          NaN

[5 rows x 36 columns]

In [4]:
all_teams_data.columns.values

array([('Unnamed: 0_level_0', 'Player'), ('Unnamed: 1_level_0', 'Nation'),
       ('Unnamed: 2_level_0', 'Pos'), ('Unnamed: 3_level_0', 'Age'),
       ('Unnamed: 4_level_0', 'MP'), ('Playing Time', 'Starts'),
       ('Playing Time', 'Min'), ('Playing Time', '90s'),
       ('Performance', 'Gls'), ('Performance', 'Ast'),
       ('Performance', 'G+A'), ('Performance', 'G-PK'),
       ('Performance', 'PK'), ('Performance', 'PKatt'),
       ('Performance', 'CrdY'), ('Performance', 'CrdR'),
       ('Expected', 'xG'), ('Expected', 'npxG'), ('Expected', 'xAG'),
       ('Expected', 'npxG+xAG'), ('Progression', 'PrgC'),
       ('Progression', 'PrgP'), ('Progression', 'PrgR'),
       ('Per 90 Minutes', 'Gls'), ('Per 90 Minutes', 'Ast'),
       ('Per 90 Minutes', 'G+A'), ('Per 90 Minutes', 'G-PK'),
       ('Per 90 Minutes', 'G+A-PK'), ('Per 90 Minutes', 'xG'),
       ('Per 90 Minutes', 'xAG'), ('Per 90 Minutes', 'xG+xAG'),
       ('Per 90 Minutes', 'npxG'), ('Per 90 Minutes', 'npxG+xAG'),
       ('Unnamed: 33_level_0', 'Matches'), ('TeamID', ''),
       ('Playing Time', 'MP')], dtype=object)

In [5]:
all_teams_data.columns = ['_'.join(col).strip() for col in all_teams_data.columns.values]

In [6]:
print(all_teams_data.columns.tolist())

['Unnamed: 0_level_0_Player', 'Unnamed: 1_level_0_Nation', 'Unnamed: 2_level_0_Pos', 'Unnamed: 3_level_0_Age', 'Unnamed: 4_level_0_MP', 'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s', 'Performance_Gls', 'Performance_Ast', 'Performance_G+A', 'Performance_G-PK', 'Performance_PK', 'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR', 'Expected_xG', 'Expected_npxG', 'Expected_xAG', 'Expected_npxG+xAG', 'Progression_PrgC', 'Progression_PrgP', 'Progression_PrgR', 'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK', 'Per 90 Minutes_xG', 'Per 90 Minutes_xAG', 'Per 90 Minutes_xG+xAG', 'Per 90 Minutes_npxG', 'Per 90 Minutes_npxG+xAG', 'Unnamed: 33_level_0_Matches', 'TeamID_', 'Playing Time_MP']

In [7]:
all_teams_data = all_teams_data.rename(columns={
    'Unnamed: 0_level_0_Player': 'player',
    'Unnamed: 1_level_0_Nation': 'nation',
    'Unnamed: 2_level_0_Pos': 'position',
    'Unnamed: 3_level_0_Age': "age",
    'Unnamed: 4_level_0_MP': "mp",
    'Playing Time_Starts': 'starts', 
    'Playing Time_Min': 'time_min', 
    'Playing Time_90s': 'time_90s', 
    'Performance_Gls': 'goals', 
    'Performance_Ast': 'assists', 
    'Performance_G+A': 'goals_assists', 
    'Performance_G-PK': 'nonpen_goals', 
    'Performance_PK': 'pk', 
    'Performance_PKatt':'pk_attempt', 
    'Performance_CrdY':'yellow', 
    'Performance_CrdR':'red', 
    'Expected_xG':'xG', 
    'Expected_npxG':'npxG', 
    'Expected_xAG':'xAG', 
    'Expected_npxG+xAG':'npxG_xAG', 
    'Progression_PrgC': 'PrgC', 
    'Progression_PrgP': 'PrgP', 
    'Progression_PrgR': 'PrgR', 
    'Per 90 Minutes_Gls':'goalsper90', 
    'Per 90 Minutes_Ast':'assistsper90', 
    'Per 90 Minutes_G+A': 'g_aper90', 
    'Per 90 Minutes_G-PK':'g_pk/90', 
    'Per 90 Minutes_G+A-PK':'g_a_pkper90', 
    'Per 90 Minutes_xG':'xG_per90', 
    'Per 90 Minutes_xAG': 'xAG_per90', 
    'Per 90 Minutes_xG+xAG': 'xG_xAG_per90', 
    'Per 90 Minutes_npxG': 'npxGper90', 
    'Per 90 Minutes_npxG+xAG': 'npxG_xAGper90', 
    'Unnamed: 33_level_0_Matches': 'Matches', 
    'TeamID_': 'team',
    'Playing Time_MP': 'Playing Time_MP'
})

In [8]:
all_teams_data.head()

,player,nation,position,age,mp,starts,time_min,time_90s,goals,assists,...,g-pk/90,g_a_pkper90,xG_per90,xAG_per90,xG_xAG_per90,npxG/90,npxG_xAGper90,Matches,team,Playing Time_MP
0,Julián Álvarez,ar ARG,"MF,FW",24-092,33.0,31,2628.0,29.2,9.0,8.0,...,0.27,0.55,0.41,0.22,0.63,0.38,0.60,Matches,Manchester-City-Stats,NaN
1,Rodri,es ESP,MF,27-315,30.0,30,2571.0,28.6,7.0,7.0,...,0.25,0.49,0.13,0.11,0.24,0.13,0.24,Matches,Manchester-City-Stats,NaN
2,Ederson,br BRA,GK,30-259,30.0,30,2537.0,28.2,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Manchester-City-Stats,NaN
3,Phil Foden,eng ENG,"FW,MF",23-340,31.0,29,2518.0,28.0,16.0,7.0,...,0.57,0.82,0.33,0.27,0.60,0.33,0.60,Matches,Manchester-City-Stats,NaN
4,Kyle Walker,eng ENG,DF,33-340,28.0,27,2428.0,27.0,0.0,4.0,...,0.00,0.15,0.01,0.10,0.11,0.01,0.11,Matches,Manchester-City-Stats,NaN

In [9]:
# change age structure
all_teams_data['age'] = all_teams_data['age'].str.split('-').str[0]

In [10]:
# Drop the 'Nation' column from the DataFrame in place
all_teams_data.drop(columns=['nation','Matches', 'Playing Time_MP', 'mp'], inplace=True)

In [11]:
#change TeamID_
all_teams_data['team'] = all_teams_data['team'].str.split('-Stats').str[0]

In [12]:
#get rid of players who hasn't started more than 7 games
all_teams_data = all_teams_data[all_teams_data['starts'] >= 7]

In [13]:
all_teams_data = all_teams_data[all_teams_data['position'] != 'GK']

In [15]:
all_teams_data.head()

,player,position,age,starts,time_min,time_90s,goals,assists,goals_assists,nonpen_goals,...,assistsper90,g_aper90,g-pk/90,g_a_pkper90,xG_per90,xAG_per90,xG_xAG_per90,npxG/90,npxG_xAGper90,team
0,Julián Álvarez,"MF,FW",24,31,2628.0,29.2,9.0,8.0,17.0,8.0,...,0.27,0.58,0.27,0.55,0.41,0.22,0.63,0.38,0.60,Manchester-City
1,Rodri,MF,27,30,2571.0,28.6,7.0,7.0,14.0,7.0,...,0.25,0.49,0.25,0.49,0.13,0.11,0.24,0.13,0.24,Manchester-City
3,Phil Foden,"FW,MF",23,29,2518.0,28.0,16.0,7.0,23.0,16.0,...,0.25,0.82,0.57,0.82,0.33,0.27,0.60,0.33,0.60,Manchester-City
4,Kyle Walker,DF,33,27,2428.0,27.0,0.0,4.0,4.0,0.0,...,0.15,0.15,0.00,0.15,0.01,0.10,0.11,0.01,0.11,Manchester-City
5,Rúben Dias,DF,26,25,2289.0,25.4,0.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.05,0.01,0.06,0.05,0.06,Manchester-City

In [16]:
# Save the combined data to a CSV file
all_teams_data.to_csv('epl_basicstats_data.csv', index=False)
print("All data has been saved to 'epl_basicstats_data.csv'.")

All data has been saved to 'epl_basicstats_data.csv'.